(ns hiccup-framework7.reagent
  (:refer-clojure :exclude [list])
  (:require [reagent.core :as reagent]))

(let [lib (->> (aget js/window "framework7-react")
               js->clj
               (map (fn [[k v]] [(keyword k) (reagent/adapt-react-class v)]))
               (into {}))]
  (def app (lib :Framework7App))
  (def status-bar (lib :Statusbar))
  (def views (lib :Views))
  (def view (lib :View))
  (def pages (lib :Pages))
  (def page (lib :Page))
  (def navbar (lib :Navbar))
  (def card (lib :Card))
  (def card-header (lib :CardHeader))
  (def card-content (lib :CardContent))
  (def card-footer (lib :CardFooter))
  (def link (lib :Link))
  (def timeline (lib :Timeline))
  (def timeline-item (lib :TimelineItem))
  (def list (lib :List))
  (def list-button (lib :ListButton))
  (def list-item (lib :ListItem))
  (def icon (lib :Icon))
  (def form-label (lib :FormLabel))
  (def form-input (lib :FormInput))
  (def tabs (lib :Tabs))
  (def tab (lib :Tab))
  (def toolbar (lib :Toolbar))
  (def sub-navbar (lib :Subnavbar))
  (def nav-right (lib :NavRight))
  (def buttons (lib :Buttons))
  (def buttons-segmented (lib :ButtonsSegmented))
  (def popover (lib :Popover))
  (def button (lib :Button)))
